import type { Metadata } from "next";
import { Roboto_Flex} from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/components/theme-provider";


const robotoFlex = Roboto_Flex({
  variable: "--font-roboto-flex",
  subsets: ["latin"],
  display: "swap",
  axes: ["wdth" , "slnt", "opsz"]
});


export const metadata: Metadata = {
  title: "CodeSwift-AutoBuild",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${robotoFlex.variable} antialiased`}
      >

        <ThemeProvider
            attribute="class"
            defaultTheme="dark"
            enableSystem
            disableTransitionOnChange
          >       
            {children}
        </ThemeProvider>
        
      </body>
    </html>
  );
}
